# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 19:17
from __future__ import unicode_literals

import aztech.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(b'ongoing', b'ongoing'), (b'completed', b'completed'), (b'future', b'future')], default=(b'ongoing', b'ongoing'), max_length=25),
        ),
        migrations.AddField(
            model_name='section',
            name='tagline',
            field=models.CharField(default='', help_text='Not more than 160 Character.', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=aztech.utils.upload_location),
        ),
    ]
