# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0002_auto_20180326_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
