# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 21:44
from __future__ import unicode_literals

import aztech.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0003_auto_20180327_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fp',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tp',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Show on Landing Page'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aztech.utils.upload_location),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aztech.utils.upload_location),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aztech.utils.upload_location),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='section',
            name='tagline',
            field=models.CharField(blank=True, help_text='Not more than 160 Character.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aztech.utils.upload_location),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
