# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0004_auto_20180412_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
