# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0005_auto_20180805_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(blank=True, max_length=300, null=True)),
                ('position', models.CharField(blank=True, max_length=300, null=True)),
                ('qualification', models.CharField(blank=True, max_length=300, null=True)),
                ('job_type', models.CharField(blank=True, help_text='Job Type: Part-Time, Full-Time,Work from Home, Freelance, etc. You can give comma separated list.', max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('no_of_position', models.CharField(blank=True, max_length=256, null=True)),
                ('experience', models.CharField(blank=True, max_length=300, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('skill_required', models.TextField(blank=True, max_length=500, null=True)),
                ('remuneration', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
