# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0005_auto_20180412_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
