# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-21 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0006_career'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
    ]
