# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0006_auto_20180412_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
