# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-04 15:17
from __future__ import unicode_literals

import aztech.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aztech', '0007_auto_20181021_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=aztech.utils.upload_location)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
            },
        ),
    ]
